const fs = require('fs');
const path = require('path');

// This is a small helper that demonstrates where you'd load the wasm prover
// and generate a proof using the compiled wasm artifact from zk/noir.
// Note: running this script requires the wasm binary & prover toolchain generated by `noirc`.

async function main(){
  const proofPath = path.join(process.cwd(),'..','..','zk','noir','proof.json');
  if(!fs.existsSync(proofPath)){
    console.error('Proof not found. Build and run `make prove` in zk/noir first.');
    process.exit(1);
  }
  const proof = JSON.parse(fs.readFileSync(proofPath));
  console.log('Loaded proof (truncated):', JSON.stringify(proof).slice(0,200));
  console.log('\nIn a fuller integration you would:');
  console.log('- load wasm prover (generated by noirc) via WebAssembly or noir js bindings');
  console.log('- call prover with private input to get a proof');
  console.log('- send the proof bytes to the verifier CPI or off-chain verifier');
}

main();
